agents:
- capacity: 3
  name: agent0
  start: !!python/tuple [30, 4]
- capacity: 3
  name: agent1
  start: &id004 !!python/tuple [34, 6]
- capacity: 3
  name: agent2
  start: !!python/tuple [35, 4]
- capacity: 3
  name: agent3
  start: !!python/tuple [32, 3]
- capacity: 3
  name: agent4
  start: !!python/tuple [35, 11]
- capacity: 3
  name: agent5
  start: !!python/tuple [30, 9]
- capacity: 3
  name: agent6
  start: &id003 !!python/tuple [33, 14]
- capacity: 3
  name: agent7
  start: &id001 !!python/tuple [33, 9]
- capacity: 3
  name: agent8
  start: !!python/tuple [35, 8]
- capacity: 3
  name: agent9
  start: !!python/tuple [34, 2]
- capacity: 3
  name: agent10
  start: &id002 !!python/tuple [33, 12]
- capacity: 3
  name: agent11
  start: !!python/tuple [30, 11]
- capacity: 3
  name: agent12
  start: !!python/tuple [31, 6]
- capacity: 3
  name: agent13
  start: &id005 !!python/tuple [35, 14]
- capacity: 3
  name: agent14
  start: !!python/tuple [34, 17]
- capacity: 3
  name: agent15
  start: !!python/tuple [32, 17]
- capacity: 3
  name: agent16
  start: !!python/tuple [30, 13]
- capacity: 3
  name: agent17
  start: !!python/tuple [32, 8]
- capacity: 3
  name: agent18
  start: !!python/tuple [35, 13]
- capacity: 3
  name: agent19
  start: !!python/tuple [32, 4]
map:
  base_points:
  - &id007 !!python/tuple [33, 5]
  - &id029 !!python/tuple [33, 6]
  - !!python/tuple [33, 7]
  - &id013 !!python/tuple [33, 8]
  - *id001
  - &id014 !!python/tuple [33, 10]
  - &id015 !!python/tuple [33, 11]
  - *id002
  - &id012 !!python/tuple [33, 13]
  - *id003
  - &id017 !!python/tuple [34, 5]
  - *id004
  - !!python/tuple [34, 7]
  - &id019 !!python/tuple [34, 8]
  - !!python/tuple [34, 9]
  - &id026 !!python/tuple [34, 10]
  - !!python/tuple [34, 11]
  - &id027 !!python/tuple [34, 12]
  - !!python/tuple [34, 13]
  - &id009 !!python/tuple [34, 14]
  - &id011 !!python/tuple [35, 5]
  - &id020 !!python/tuple [35, 6]
  - &id024 !!python/tuple [35, 7]
  - &id018 !!python/tuple [35, 8]
  - &id008 !!python/tuple [35, 9]
  - &id033 !!python/tuple [35, 10]
  - &id006 !!python/tuple [35, 11]
  - &id023 !!python/tuple [35, 12]
  - &id010 !!python/tuple [35, 13]
  - *id005
  dimensions: !!python/tuple [36, 20]
  non_task_endpoints:
  - !!python/tuple [34, 3]
  - !!python/tuple [33, 2]
  - !!python/tuple [33, 4]
  - !!python/tuple [35, 18]
  - !!python/tuple [35, 15]
  - !!python/tuple [34, 15]
  - !!python/tuple [33, 3]
  - !!python/tuple [35, 16]
  - !!python/tuple [33, 15]
  - !!python/tuple [33, 16]
  - !!python/tuple [34, 17]
  - !!python/tuple [35, 2]
  - !!python/tuple [35, 4]
  - !!python/tuple [33, 17]
  - !!python/tuple [35, 3]
  - !!python/tuple [34, 1]
  - !!python/tuple [34, 4]
  - !!python/tuple [35, 1]
  - !!python/tuple [34, 18]
  - !!python/tuple [33, 1]
  obstacles:
  - !!python/tuple [1, 2]
  - !!python/tuple [1, 1]
  - !!python/tuple [2, 2]
  - !!python/tuple [1, 6]
  - !!python/tuple [1, 5]
  - !!python/tuple [2, 6]
  - !!python/tuple [1, 10]
  - !!python/tuple [1, 9]
  - !!python/tuple [2, 10]
  - !!python/tuple [1, 14]
  - !!python/tuple [1, 13]
  - !!python/tuple [2, 14]
  - !!python/tuple [5, 2]
  - !!python/tuple [5, 1]
  - !!python/tuple [6, 2]
  - !!python/tuple [5, 6]
  - !!python/tuple [5, 5]
  - !!python/tuple [6, 6]
  - !!python/tuple [5, 10]
  - !!python/tuple [5, 9]
  - !!python/tuple [6, 10]
  - !!python/tuple [5, 14]
  - !!python/tuple [5, 13]
  - !!python/tuple [6, 14]
  - !!python/tuple [9, 2]
  - !!python/tuple [9, 1]
  - !!python/tuple [10, 2]
  - !!python/tuple [9, 6]
  - !!python/tuple [9, 5]
  - !!python/tuple [10, 6]
  - !!python/tuple [9, 10]
  - !!python/tuple [9, 9]
  - !!python/tuple [10, 10]
  - !!python/tuple [9, 14]
  - !!python/tuple [9, 13]
  - !!python/tuple [10, 14]
  - !!python/tuple [13, 2]
  - !!python/tuple [13, 1]
  - !!python/tuple [14, 2]
  - !!python/tuple [13, 6]
  - !!python/tuple [13, 5]
  - !!python/tuple [14, 6]
  - !!python/tuple [13, 10]
  - !!python/tuple [13, 9]
  - !!python/tuple [14, 10]
  - !!python/tuple [13, 14]
  - !!python/tuple [13, 13]
  - !!python/tuple [14, 14]
  - !!python/tuple [17, 2]
  - !!python/tuple [17, 1]
  - !!python/tuple [18, 2]
  - !!python/tuple [17, 6]
  - !!python/tuple [17, 5]
  - !!python/tuple [18, 6]
  - !!python/tuple [17, 10]
  - !!python/tuple [17, 9]
  - !!python/tuple [18, 10]
  - !!python/tuple [17, 14]
  - !!python/tuple [17, 13]
  - !!python/tuple [18, 14]
  - !!python/tuple [21, 2]
  - !!python/tuple [21, 1]
  - !!python/tuple [22, 2]
  - !!python/tuple [21, 6]
  - !!python/tuple [21, 5]
  - !!python/tuple [22, 6]
  - !!python/tuple [21, 10]
  - !!python/tuple [21, 9]
  - !!python/tuple [22, 10]
  - !!python/tuple [21, 14]
  - !!python/tuple [21, 13]
  - !!python/tuple [22, 14]
  - !!python/tuple [25, 2]
  - !!python/tuple [25, 1]
  - !!python/tuple [26, 2]
  - !!python/tuple [25, 6]
  - !!python/tuple [25, 5]
  - !!python/tuple [26, 6]
  - !!python/tuple [25, 10]
  - !!python/tuple [25, 9]
  - !!python/tuple [26, 10]
  - !!python/tuple [25, 14]
  - !!python/tuple [25, 13]
  - !!python/tuple [26, 14]
  - !!python/tuple [29, 2]
  - !!python/tuple [29, 1]
  - !!python/tuple [30, 2]
  - !!python/tuple [29, 6]
  - !!python/tuple [29, 5]
  - !!python/tuple [30, 6]
  - !!python/tuple [29, 10]
  - !!python/tuple [29, 9]
  - !!python/tuple [30, 10]
  - !!python/tuple [29, 14]
  - !!python/tuple [29, 13]
  - !!python/tuple [30, 14]
tasks:
- goal: *id006
  start: !!python/tuple [13, 16]
  start_time: 0
  task_name: task0
- goal: *id001
  start: !!python/tuple [11, 17]
  start_time: 0
  task_name: task1
- goal: !!python/tuple [35, 3]
  start: !!python/tuple [28, 9]
  start_time: 0
  task_name: task2
- goal: *id005
  start: !!python/tuple [28, 3]
  start_time: 0
  task_name: task3
- goal: !!python/tuple [35, 5]
  start: !!python/tuple [11, 5]
  start_time: 1
  task_name: task4
- goal: !!python/tuple [35, 7]
  start: !!python/tuple [27, 3]
  start_time: 1
  task_name: task5
- goal: *id007
  start: !!python/tuple [28, 5]
  start_time: 1
  task_name: task6
- goal: *id008
  start: !!python/tuple [11, 18]
  start_time: 1
  task_name: task7
- goal: !!python/tuple [35, 4]
  start: &id028 !!python/tuple [2, 5]
  start_time: 2
  task_name: task8
- goal: *id009
  start: &id016 !!python/tuple [27, 15]
  start_time: 2
  task_name: task9
- goal: !!python/tuple [35, 16]
  start: !!python/tuple [20, 12]
  start_time: 2
  task_name: task10
- goal: *id010
  start: !!python/tuple [23, 6]
  start_time: 2
  task_name: task11
- goal: !!python/tuple [35, 3]
  start: &id021 !!python/tuple [18, 9]
  start_time: 3
  task_name: task12
- goal: !!python/tuple [35, 9]
  start: !!python/tuple [24, 4]
  start_time: 3
  task_name: task13
- goal: *id011
  start: !!python/tuple [26, 1]
  start_time: 3
  task_name: task14
- goal: *id012
  start: !!python/tuple [0, 1]
  start_time: 3
  task_name: task15
- goal: !!python/tuple [35, 4]
  start: &id031 !!python/tuple [24, 19]
  start_time: 3
  task_name: task16
- goal: *id013
  start: !!python/tuple [17, 7]
  start_time: 3
  task_name: task17
- goal: *id006
  start: !!python/tuple [7, 1]
  start_time: 4
  task_name: task18
- goal: !!python/tuple [35, 4]
  start: !!python/tuple [0, 8]
  start_time: 4
  task_name: task19
- goal: !!python/tuple [35, 6]
  start: !!python/tuple [28, 13]
  start_time: 4
  task_name: task20
- goal: !!python/tuple [35, 2]
  start: !!python/tuple [4, 5]
  start_time: 4
  task_name: task21
- goal: !!python/tuple [35, 15]
  start: &id034 !!python/tuple [32, 6]
  start_time: 4
  task_name: task22
- goal: !!python/tuple [35, 3]
  start: !!python/tuple [12, 15]
  start_time: 4
  task_name: task23
- goal: !!python/tuple [35, 10]
  start: !!python/tuple [12, 2]
  start_time: 4
  task_name: task24
- goal: !!python/tuple [35, 3]
  start: !!python/tuple [27, 7]
  start_time: 5
  task_name: task25
- goal: !!python/tuple [35, 4]
  start: !!python/tuple [8, 9]
  start_time: 5
  task_name: task26
- goal: *id014
  start: &id025 !!python/tuple [22, 17]
  start_time: 5
  task_name: task27
- goal: *id015
  start: *id016
  start_time: 5
  task_name: task28
- goal: *id005
  start: !!python/tuple [31, 4]
  start_time: 5
  task_name: task29
- goal: *id007
  start: &id022 !!python/tuple [18, 17]
  start_time: 5
  task_name: task30
- goal: *id017
  start: !!python/tuple [21, 11]
  start_time: 5
  task_name: task31
- goal: !!python/tuple [35, 1]
  start: !!python/tuple [1, 11]
  start_time: 6
  task_name: task32
- goal: *id018
  start: !!python/tuple [17, 0]
  start_time: 6
  task_name: task33
- goal: *id019
  start: !!python/tuple [20, 1]
  start_time: 7
  task_name: task34
- goal: *id001
  start: &id030 !!python/tuple [17, 17]
  start_time: 7
  task_name: task35
- goal: *id004
  start: !!python/tuple [26, 0]
  start_time: 7
  task_name: task36
- goal: *id020
  start: *id021
  start_time: 8
  task_name: task37
- goal: *id018
  start: &id035 !!python/tuple [23, 0]
  start_time: 8
  task_name: task38
- goal: !!python/tuple [35, 12]
  start: !!python/tuple [16, 3]
  start_time: 8
  task_name: task39
- goal: !!python/tuple [35, 16]
  start: *id022
  start_time: 8
  task_name: task40
- goal: !!python/tuple [35, 18]
  start: !!python/tuple [4, 14]
  start_time: 8
  task_name: task41
- goal: !!python/tuple [35, 9]
  start: !!python/tuple [24, 5]
  start_time: 8
  task_name: task42
- goal: *id023
  start: !!python/tuple [24, 2]
  start_time: 8
  task_name: task43
- goal: !!python/tuple [35, 13]
  start: !!python/tuple [20, 9]
  start_time: 8
  task_name: task44
- goal: *id024
  start: !!python/tuple [24, 11]
  start_time: 9
  task_name: task45
- goal: !!python/tuple [35, 3]
  start: !!python/tuple [6, 0]
  start_time: 9
  task_name: task46
- goal: *id009
  start: !!python/tuple [10, 5]
  start_time: 9
  task_name: task47
- goal: !!python/tuple [35, 9]
  start: *id025
  start_time: 9
  task_name: task48
- goal: *id026
  start: !!python/tuple [12, 11]
  start_time: 9
  task_name: task49
- goal: *id027
  start: !!python/tuple [21, 7]
  start_time: 10
  task_name: task50
- goal: *id013
  start: !!python/tuple [21, 0]
  start_time: 10
  task_name: task51
- goal: *id020
  start: &id032 !!python/tuple [3, 17]
  start_time: 10
  task_name: task52
- goal: *id009
  start: *id028
  start_time: 10
  task_name: task53
- goal: *id006
  start: !!python/tuple [11, 19]
  start_time: 10
  task_name: task54
- goal: !!python/tuple [35, 1]
  start: !!python/tuple [32, 7]
  start_time: 10
  task_name: task55
- goal: !!python/tuple [35, 12]
  start: !!python/tuple [24, 17]
  start_time: 10
  task_name: task56
- goal: *id026
  start: !!python/tuple [2, 11]
  start_time: 10
  task_name: task57
- goal: !!python/tuple [35, 13]
  start: !!python/tuple [32, 18]
  start_time: 10
  task_name: task58
- goal: !!python/tuple [35, 10]
  start: !!python/tuple [11, 3]
  start_time: 11
  task_name: task59
- goal: *id011
  start: !!python/tuple [9, 19]
  start_time: 11
  task_name: task60
- goal: !!python/tuple [35, 18]
  start: !!python/tuple [14, 16]
  start_time: 11
  task_name: task61
- goal: *id026
  start: !!python/tuple [15, 5]
  start_time: 11
  task_name: task62
- goal: !!python/tuple [35, 9]
  start: !!python/tuple [7, 15]
  start_time: 11
  task_name: task63
- goal: !!python/tuple [35, 13]
  start: !!python/tuple [28, 6]
  start_time: 11
  task_name: task64
- goal: *id029
  start: *id030
  start_time: 11
  task_name: task65
- goal: !!python/tuple [35, 10]
  start: !!python/tuple [32, 16]
  start_time: 12
  task_name: task66
- goal: *id006
  start: !!python/tuple [17, 8]
  start_time: 12
  task_name: task67
- goal: *id003
  start: !!python/tuple [23, 16]
  start_time: 12
  task_name: task68
- goal: *id024
  start: !!python/tuple [18, 1]
  start_time: 13
  task_name: task69
- goal: *id010
  start: *id031
  start_time: 13
  task_name: task70
- goal: *id024
  start: !!python/tuple [29, 0]
  start_time: 13
  task_name: task71
- goal: !!python/tuple [35, 13]
  start: *id016
  start_time: 13
  task_name: task72
- goal: !!python/tuple [35, 5]
  start: *id032
  start_time: 13
  task_name: task73
- goal: *id005
  start: !!python/tuple [29, 11]
  start_time: 13
  task_name: task74
- goal: !!python/tuple [35, 3]
  start: !!python/tuple [18, 18]
  start_time: 13
  task_name: task75
- goal: *id004
  start: !!python/tuple [22, 9]
  start_time: 13
  task_name: task76
- goal: !!python/tuple [35, 14]
  start: !!python/tuple [3, 19]
  start_time: 13
  task_name: task77
- goal: *id033
  start: !!python/tuple [3, 13]
  start_time: 13
  task_name: task78
- goal: !!python/tuple [35, 3]
  start: *id034
  start_time: 13
  task_name: task79
- goal: *id027
  start: !!python/tuple [23, 4]
  start_time: 13
  task_name: task80
- goal: !!python/tuple [35, 4]
  start: !!python/tuple [19, 0]
  start_time: 14
  task_name: task81
- goal: *id026
  start: !!python/tuple [32, 19]
  start_time: 14
  task_name: task82
- goal: *id007
  start: !!python/tuple [12, 18]
  start_time: 14
  task_name: task83
- goal: *id009
  start: !!python/tuple [3, 16]
  start_time: 14
  task_name: task84
- goal: !!python/tuple [35, 4]
  start: !!python/tuple [9, 18]
  start_time: 14
  task_name: task85
- goal: !!python/tuple [35, 15]
  start: !!python/tuple [25, 8]
  start_time: 15
  task_name: task86
- goal: *id004
  start: !!python/tuple [24, 6]
  start_time: 15
  task_name: task87
- goal: !!python/tuple [35, 13]
  start: !!python/tuple [10, 3]
  start_time: 15
  task_name: task88
- goal: !!python/tuple [35, 16]
  start: !!python/tuple [3, 0]
  start_time: 15
  task_name: task89
- goal: *id023
  start: !!python/tuple [12, 0]
  start_time: 15
  task_name: task90
- goal: !!python/tuple [35, 12]
  start: !!python/tuple [17, 19]
  start_time: 15
  task_name: task91
- goal: *id017
  start: !!python/tuple [7, 6]
  start_time: 15
  task_name: task92
- goal: !!python/tuple [35, 7]
  start: !!python/tuple [20, 16]
  start_time: 16
  task_name: task93
- goal: !!python/tuple [35, 17]
  start: !!python/tuple [21, 12]
  start_time: 16
  task_name: task94
- goal: !!python/tuple [35, 11]
  start: *id035
  start_time: 16
  task_name: task95
- goal: *id017
  start: !!python/tuple [0, 15]
  start_time: 17
  task_name: task96
- goal: !!python/tuple [35, 14]
  start: !!python/tuple [8, 6]
  start_time: 17
  task_name: task97
- goal: !!python/tuple [35, 12]
  start: !!python/tuple [4, 15]
  start_time: 17
  task_name: task98
- goal: *id003
  start: !!python/tuple [11, 7]
  start_time: 17
  task_name: task99
