agents:
-   start: !!python/tuple [0, 1]
    name: agent0
    capacity: 2
-   start: !!python/tuple [2, 0]
    name: agent1
    capacity: 2
map:
    dimensions: [10, 3]
    obstacles:
    - !!python/tuple [1, 1]
    - !!python/tuple [2, 1]
    - !!python/tuple [3, 1]
    - !!python/tuple [4, 1]
    - !!python/tuple [5, 1]
    - !!python/tuple [6, 1]
    - !!python/tuple [7, 1]
    non_task_endpoints:
    - !!python/tuple [9, 2]
    - !!python/tuple [9, 1]
    base_points:
    - !!python/tuple [0, 0] 
    - !!python/tuple [0, 1]
tasks:
-   start_time: 2
    start: !!python/tuple [0, 1]
    goal: !!python/tuple [8, 1]
    task_name: task0
-   start_time: 2
    start: !!python/tuple [2, 0]
    goal: !!python/tuple [9, 0]
    task_name: task1
