agents:
-   start: !!python/tuple [0, 1]
    name: agent0
    capacity: 2
-   start: !!python/tuple [0, 5]
    name: agent1
    capacity: 2
-   start: !!python/tuple [0, 7]
    name: agent2
    capacity: 2
-   start: !!python/tuple [0, 9]
    name: agent3
    capacity: 2
-   start: !!python/tuple [0, 11]
    name: agent4
    capacity: 2
-   start: !!python/tuple [0, 15]
    name: agent5
    capacity: 2
-   start: !!python/tuple [24, 1]
    name: agent6
    capacity: 2
-   start: !!python/tuple [24, 5]
    name: agent7
    capacity: 2
-   start: !!python/tuple [24, 7]
    name: agent8
    capacity: 2
-   start: !!python/tuple [24, 9]
    name: agent9
    capacity: 2
-   start: !!python/tuple [24, 11]
    name: agent10
    capacity: 2
-   start: !!python/tuple [24, 15]
    name: agent11
    capacity: 2
map:
    dimensions: !!python/tuple [25, 17]
    obstacles:
    - !!python/tuple [3, 2]
    - !!python/tuple [4, 2]
    - !!python/tuple [5, 2]
    - !!python/tuple [6, 2]
    - !!python/tuple [7, 2]
    - !!python/tuple [8, 2]
    - !!python/tuple [9, 2]
    - !!python/tuple [10, 2]
    - !!python/tuple [11, 2]
    - !!python/tuple [3, 1]
    - !!python/tuple [3, 3]
    - !!python/tuple [5, 1]
    - !!python/tuple [5, 3]
    - !!python/tuple [7, 1]
    - !!python/tuple [7, 3]
    - !!python/tuple [9, 1]
    - !!python/tuple [9, 3]
    - !!python/tuple [11, 1]
    - !!python/tuple [11, 3]
    - !!python/tuple [3, 6]
    - !!python/tuple [4, 6]
    - !!python/tuple [5, 6]
    - !!python/tuple [6, 6]
    - !!python/tuple [7, 6]
    - !!python/tuple [8, 6]
    - !!python/tuple [9, 6]
    - !!python/tuple [10, 6]
    - !!python/tuple [11, 6]
    - !!python/tuple [3, 5]
    - !!python/tuple [3, 7]
    - !!python/tuple [5, 5]
    - !!python/tuple [5, 7]
    - !!python/tuple [7, 5]
    - !!python/tuple [7, 7]
    - !!python/tuple [9, 5]
    - !!python/tuple [9, 7]
    - !!python/tuple [11, 5]
    - !!python/tuple [11, 7]
    - !!python/tuple [3, 10]
    - !!python/tuple [4, 10]
    - !!python/tuple [5, 10]
    - !!python/tuple [6, 10]
    - !!python/tuple [7, 10]
    - !!python/tuple [8, 10]
    - !!python/tuple [9, 10]
    - !!python/tuple [10, 10]
    - !!python/tuple [11, 10]
    - !!python/tuple [3, 9]
    - !!python/tuple [3, 11]
    - !!python/tuple [7, 14]
    - !!python/tuple [8, 14]
    - !!python/tuple [9, 14]
    - !!python/tuple [10, 14]
    - !!python/tuple [11, 14]
    - !!python/tuple [3, 13]
    - !!python/tuple [3, 15]
    - !!python/tuple [5, 13]
    - !!python/tuple [5, 15]
    - !!python/tuple [7, 13]
    - !!python/tuple [7, 15]
    - !!python/tuple [9, 13]
    - !!python/tuple [9, 15]
    - !!python/tuple [11, 13]
    - !!python/tuple [11, 15]
    - !!python/tuple [13, 2]
    - !!python/tuple [14, 2]
    - !!python/tuple [15, 2]
    - !!python/tuple [16, 2]
    - !!python/tuple [17, 2]
    - !!python/tuple [18, 2]
    - !!python/tuple [19, 2]
    - !!python/tuple [20, 2]
    - !!python/tuple [21, 2]
    - !!python/tuple [13, 1]
    - !!python/tuple [13, 3]
    - !!python/tuple [15, 1]
    - !!python/tuple [15, 3]
    - !!python/tuple [17, 1]
    - !!python/tuple [17, 3]
    - !!python/tuple [19, 1]
    - !!python/tuple [19, 3]
    - !!python/tuple [21, 1]
    - !!python/tuple [21, 3]
    - !!python/tuple [13, 6]
    - !!python/tuple [14, 6]
    - !!python/tuple [15, 6]
    - !!python/tuple [16, 6]
    - !!python/tuple [17, 6]
    - !!python/tuple [18, 6]
    - !!python/tuple [19, 6]
    - !!python/tuple [20, 6]
    - !!python/tuple [21, 6]
    - !!python/tuple [13, 5]
    - !!python/tuple [13, 7]
    - !!python/tuple [15, 5]
    - !!python/tuple [15, 7]
    - !!python/tuple [17, 5]
    - !!python/tuple [17, 7]
    - !!python/tuple [19, 5]
    - !!python/tuple [19, 7]
    - !!python/tuple [21, 5]
    - !!python/tuple [21, 7]
    - !!python/tuple [13, 10]
    - !!python/tuple [14, 10]
    - !!python/tuple [15, 10]
    - !!python/tuple [16, 10]
    - !!python/tuple [17, 10]
    - !!python/tuple [18, 10]
    - !!python/tuple [19, 10]
    - !!python/tuple [20, 10]
    - !!python/tuple [21, 10]
    - !!python/tuple [13, 9]
    - !!python/tuple [13, 11]
    - !!python/tuple [15, 9]
    - !!python/tuple [15, 11]
    - !!python/tuple [17, 9]
    - !!python/tuple [17, 11]
    - !!python/tuple [19, 9]
    - !!python/tuple [19, 11]
    - !!python/tuple [21, 9]
    - !!python/tuple [21, 11]
    - !!python/tuple [13, 14]
    - !!python/tuple [14, 14]
    - !!python/tuple [15, 14]
    - !!python/tuple [16, 14]
    - !!python/tuple [17, 14]
    - !!python/tuple [18, 14]
    - !!python/tuple [19, 14]
    - !!python/tuple [20, 14]
    - !!python/tuple [21, 14]
    - !!python/tuple [13, 13]
    - !!python/tuple [13, 15]
    - !!python/tuple [15, 13]
    - !!python/tuple [15, 15]
    - !!python/tuple [17, 13]
    - !!python/tuple [17, 15]
    - !!python/tuple [19, 13]
    - !!python/tuple [19, 15]
    - !!python/tuple [21, 13]
    - !!python/tuple [21, 15]
    non_task_endpoints:
    - !!python/tuple [0, 1]
    - !!python/tuple [0, 5]
    - !!python/tuple [0, 7]
    - !!python/tuple [0, 9]
    - !!python/tuple [0, 11]
    - !!python/tuple [0, 15]
    - !!python/tuple [24, 1]
    - !!python/tuple [24, 5]
    - !!python/tuple [24, 7]
    - !!python/tuple [24, 9]
    - !!python/tuple [24, 11]
    - !!python/tuple [24, 15]
    start_locations:
    -   !!python/tuple [4, 1]
    -   !!python/tuple [6, 1]
    -   !!python/tuple [8, 1]
    -   !!python/tuple [10, 1]
    -   !!python/tuple [4, 3]
    -   !!python/tuple [6, 3]
    -   !!python/tuple [8, 3]
    -   !!python/tuple [10, 3]
    -   !!python/tuple [4, 5]
    -   !!python/tuple [6, 5]
    -   !!python/tuple [8, 5]
    -   !!python/tuple [10, 5]
    -   !!python/tuple [4, 7]
    -   !!python/tuple [6, 7]
    -   !!python/tuple [8, 7]
    -   !!python/tuple [10, 7]
    -   !!python/tuple [4, 9]
    -   !!python/tuple [6, 9]
    -   !!python/tuple [8, 9]
    -   !!python/tuple [10, 9]
    -   !!python/tuple [4, 11]
    -   !!python/tuple [6, 11]
    -   !!python/tuple [8, 11]
    -   !!python/tuple [10, 11]
    -   !!python/tuple [4, 13]
    -   !!python/tuple [6, 13]
    -   !!python/tuple [8, 13]
    -   !!python/tuple [10, 13]
    -   !!python/tuple [4, 15]
    -   !!python/tuple [6, 15]
    -   !!python/tuple [8, 15]
    -   !!python/tuple [10, 15]
    -   !!python/tuple [14, 1]
    -   !!python/tuple [16, 1]
    -   !!python/tuple [18, 1]
    -   !!python/tuple [20, 1]
    -   !!python/tuple [14, 3]
    -   !!python/tuple [16, 3]
    -   !!python/tuple [18, 3]
    -   !!python/tuple [20, 3]
    -   !!python/tuple [14, 5]
    -   !!python/tuple [16, 5]
    -   !!python/tuple [18, 5]
    -   !!python/tuple [20, 5]
    -   !!python/tuple [14, 7]
    -   !!python/tuple [16, 7]
    -   !!python/tuple [18, 7]
    -   !!python/tuple [20, 7]
    -   !!python/tuple [14, 9]
    -   !!python/tuple [16, 9]
    -   !!python/tuple [18, 9]
    -   !!python/tuple [20, 9]
    -   !!python/tuple [14, 11]
    -   !!python/tuple [16, 11]
    -   !!python/tuple [18, 11]
    -   !!python/tuple [20, 11]
    -   !!python/tuple [14, 13]
    -   !!python/tuple [16, 13]
    -   !!python/tuple [18, 13]
    -   !!python/tuple [20, 13]
    -   !!python/tuple [14, 15]
    -   !!python/tuple [16, 15]
    -   !!python/tuple [18, 15]
    -   !!python/tuple [20, 15]
    goal_locations:
    -   !!python/tuple [0, 2]
    -   !!python/tuple [0, 3]
    -   !!python/tuple [0, 4]
    -   !!python/tuple [0, 6]
    -   !!python/tuple [0, 8]
    -   !!python/tuple [0, 10]
    -   !!python/tuple [0, 12]
    -   !!python/tuple [0, 13]
    -   !!python/tuple [0, 14]
    -   !!python/tuple [24, 2]
    -   !!python/tuple [24, 3]
    -   !!python/tuple [24, 4]
    -   !!python/tuple [24, 6]
    -   !!python/tuple [24, 8]
    -   !!python/tuple [24, 10]
    -   !!python/tuple [24, 12]
    -   !!python/tuple [24, 13]
    -   !!python/tuple [24, 14]
n_tasks: 50
task_freq: 1
